export const demoData = {
	label_page: {
		Welcome: 0,
		"Example Page": 14,
	},
	pages: [0, 14],
	pinned: [0],
	blocks: [
		{
			id: 0,
			content: "Welcome",
			plainText: "",
			type: "text",
			blocks: [1, 7, 6, 2, 9, 13, 17],
		},
		{
			id: 1,
			content: `This is a temporary web demo.`,
			plainText: "",
			type: "text",
			blocks: [],
		},

		{
			id: 2,
			content: `If you hit Tab in an item, it will go one level deeper.`,
			plainText: "",
			type: "text",
			blocks: [3],
		},
		{
			id: 3,
			content: `If you hit Shift+Tab in an item, that will move it in the opposite direction.`,
			plainText: "",
			type: "text",
			blocks: [],
		},
		{
			id: 4,
			content: ``,
			plainText: "",
			type: "text",
			blocks: [],
		},
		{
			id: 5,
			content: ``,
			plainText: "",
			type: "text",
			blocks: [],
		},
		{
			id: 6,
			content: `To create a new bullet, just hit Enter on your keyboard`,
			plainText: "",
			type: "text",
			blocks: [],
		},
		{
			id: 7,
			content: `Bullets can be infinitely nested`,
			plainText: "",
			type: "text",
			blocks: [8],
		},
		{
			id: 8,
			content: `And you can click on any bullet to focus on it`,
			plainText: "",
			type: "text",
			blocks: [],
		},
		{
			id: 9,
			content: `Click the arrow to the left of a bullet to expand or collapse it`,
			plainText: "",
			collapsed: true,
			type: "text",
			blocks: [10],
		},
		{
			id: 10,
			content: `You can also move and reorganize a bullet by dragging it around`,
			plainText: "",
			type: "text",
			blocks: [],
		},
		{
			id: 11,
			content: `Use double-brackets [[ to link to a page`,
			plainText: "",
			type: "text",
			blocks: [],
		},
		{
			id: 12,
			content: `Click on a link to open the page: [[{{{14}}}]]`,
			plainText: "",
			type: "text",
			blocks: [],
		},
		{
			id: 13,
			content: `## Bi-directional linking`,
			plainText: "",
			type: "text",
			blocks: [11, 12],
		},
		{
			id: 14,
			content: `Example Page`,
			plainText: "",
			type: "text",
			blocks: [15, 16],
		},
		{
			id: 15,
			content: `All items that link to a page are attached as linked references`,
			plainText: "",
			type: "text",
			blocks: [],
		},
		{
			id: 16,
			content: `Use Alt + ArrowLeft to go to the previous page`,
			plainText: "",
			type: "text",
			blocks: [],
		},
		{
			id: 17,
			content: `## Formatting`,
			plainText: "",
			type: "text",
			blocks: [18, 21],
		},
		{
			id: 18,
			content: `Prepend an item with # followed by a space to make it a headline`,
			plainText: "",
			type: "text",
			blocks: [],
		},
		{
			id: 19,
			content: ``,
			plainText: "",
			type: "text",
			blocks: [],
		},
		{
			id: 20,
			content: `This should be enough to get you started`,
			plainText: "",
			type: "text",
			blocks: [],
		},
		{
			id: 21,
			content: `Surround text with ** to make it bold (without spaces between asterik and text)`,
			plainText: "",
			type: "text",
			blocks: [],
		},
	],
	links: [{ source: 0, block_id: 12, target: 14 }],
};
